spring:
  application:
    name: user-service
  data:
    mongodb:
<<<<<<< HEAD
      # use this while running using docker compose
      #uri: mongodb://mongodb:27017/userdb
      # use this while running locally
=======
>>>>>>> 03747c0ae9375dfcdf6de240e7dc021ce6901d4d
      uri: mongodb://localhost:27017/userdb

server:
  port: 8081


# user this while running docker-composee
#eureka:
#  client:
#    service-url:
#      defaultZone: http://service-registry:8761/eureka/

# use this while running with locally
eureka:
  client:
    service-url:
<<<<<<< HEAD
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
=======
      defaultZone: http://localhost:8761/eureka/
>>>>>>> 03747c0ae9375dfcdf6de240e7dc021ce6901d4d
