server:
  port: 8083

spring:
  application:
    name: appointmentAvailability
  data:
    uri: mongodb://mongodb:27017/appointmentAvailability

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/